version: '2'
services:
  main:
    build: .
    image: registry.gitlab.com/notch8/atla_digital_library
    env_file:
      - .env
    volumes:
      - .:/app

  sidekiq:
    extends: main
    command: sidekiq -q ingest -q default -q event
    depends_on:
      - redis
      - solr
      - fcrepo
      - postgres

  web:
    extends: main
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - sidekiq
      - redis
      - solr
      - fcrepo
      - postgres

  redis:
    image: redis:3
    ports:
      - '6379'
    volumes:
      - 'redis:/data'

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - "5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  solr:
    image: solr:5.5
    ports:
      - "8983:8983"
    volumes:
      - './solr/config:/opt/config'

  fcrepo:
    image: botimer/fcrepo:4.5.1
    volumes:
      - 'fcrepo:/opt/data'
    ports:
      - "8984:8080"

volumes:
  fcrepo:
  postgres:
  redis:
