version: '2.2'
services:
  main:
    build: .
    image: registry.gitlab.com/notch8/atla_digital_library:latest
    env_file:
      - .env.development
      - .env
    stdin_open: true
    tty: true
    volumes:
      - .:/data:delegated

  dj:
    extends: main
    command: bash -l -c "yarn install && bin/rails jobs:work"
    depends_on:
      - solr
      - fcrepo
      - postgres
      - redis

  web:
    extends: main
    command: bash -l -c "yarn install && bin/rails server --port 3000 --binding 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      VIRTUAL_HOST: atla.docker
      VIRTUAL_PORT: 3000
    depends_on:
      - dj
      - redis
      - solr
      - fcrepo
      - postgres

  redis:
    image: redis:3
    ports:
      - '6379'
    volumes:
      - 'redis:/data'

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - "5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  solr:
    image: solr:7.7
    ports:
      - "8983"
    environment:
      VIRTUAL_HOST: solr.atla.docker
      VIRTUAL_PORT: 8983
      OOM: script
    volumes:
      - './solr/conf:/opt/config:delegated'
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - "${SOLR_CORE}"
      - /opt/config

  fcrepo:
    image: botimer/fcrepo:4.5.1
    volumes:
      - 'fcrepo:/opt/data'
    ports:
      - "8080"

volumes:
  fcrepo:
  postgres:
  redis:
  solr:
