version: '3.4'

x-app: &app
  build:
    context: .
    target: hyrax-base
  # command: sh -l -c "bundle && bundle exec puma -v -b tcp://0.0.0.0:3000"
  image: ghcr.io/scientist-softserv/atla_digital_library:${TAG:-latest}
  env_file:
    - .env.development
    - .env
  # NOTE: all common env variables moved to .env
  volumes:
    - uploads:/app/samvera/hyrax-webapp/public/uploads
    - assets:/app/samvera/hyrax-webapp/public/assets
    - cache:/app/samvera/hyrax-webapp/tmp/cache
    - node:/data/node_modules
    - .:/app/samvera/hyrax-webapp

services:
  worker:
    # command: sh -l -c "bundle && bundle exec sidekiq"
    <<: *app
    build:
      context: .
      target: hyrax-worker
      cache_from:
        - ghcr.io/scientist-softserv/atla_digital_library:${TAG:-latest}
        - ghcr.io/scientist-softserv/atla_digital_library/worker:${TAG:-latest}
    image: ghcr.io/scientist-softserv/atla_digital_library/worker:${TAG:-latest}
    command: bash -l -c "bundle && yarn install && bin/rails jobs:work"
    depends_on:
      - solr
      - fcrepo
      - postgres
      - redis

  web:
    <<: *app
    command: sh -l -c "bundle && yarn install && bundle exec puma -v -b tcp://0.0.0.0:3000"
    # ports:
    #   - "3000:3000"
    environment:
      VIRTUAL_HOST: atla.test
      VIRTUAL_PORT: 3000
    depends_on:
      - worker
      - redis
      - solr
      - fcrepo
      - postgres

  redis:
    image: redis:3
    ports:
      - '6379'
    volumes:
      - 'redis:/data'

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: "${DATABASE_USER}"
    ports:
      - "5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  solr:
    image: solr:7.7
    ports:
      - "8983"
    environment:
      VIRTUAL_HOST: solr.atla.test
      VIRTUAL_PORT: 8983
      OOM: script
    volumes:
      - './solr/conf:/opt/config:delegated'
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - "${SOLR_CORE}"
      - /opt/config

  fcrepo:
    image: botimer/fcrepo:4.5.1
    volumes:
      - 'fcrepo:/opt/data'
    ports:
      - "8080"

volumes:
  fcrepo:
  postgres:
  redis:
  solr:
  uploads:
  assets:
  cache:
  node: