---
homepage:
  collections:
    - id: 1
      anchor_text: Latin America Collection - Princeton Theological Seminary
      url: /collections/latin-america-collection #PATH TO COLLECTION
      image:
        path_to_file: /img/latin_america.png #DESIRED THUMBNAIL NAME
    - id: 2
      anchor_text: Moffett Korea Collection - Princeton Theological Seminary
      url: /collections/moffett-korea-collection #PATH TO COLLECTION
      image:
        path_to_file: /img/moffett_korea.png #DESIRED THUMBNAIL NAME
    - id: 3
      anchor_text: T.F. Torrance Collection of Antiquarian Books - Princeton Theological Seminary
      url: /collections/t-f-torrance-collection-of-antiquarian-books #PATH TO COLLECTION
      image:
        path_to_file: /img/tf_torrance.png #DESIRED THUMBNAIL NAME
    - id: 4
      anchor_text: The W. H. Dub Jackson Digital Materials Collection - Southwestern Baptist Theological Seminary Libraries
      url: /collections/the-w-h-dub-jackson-digital-materials-collection #PATH TO COLLECTION
      image:
        path_to_file: /img/whdub.png #DESIRED THUMBNAIL NAME
    - id: 5
      anchor_text: The L.R. Scarborough Digital Materials Collection - Southwestern Baptist Theological Seminary Libraries
      url: /collections/the-l-r-scarborough-digital-materials-collection #PATH TO COLLECTION
      image:
        path_to_file: /img/lrscarborough.png #DESIRED THUMBNAIL NAME
    - id: 6
      anchor_text: Robert Hamill Nassau Manuscript Collection - Princeton Theological Seminary
      url: /collections/robert-hamill-nassau-manuscript-collection #PATH TO COLLECTION
      image:
        path_to_file: /img/robert_hamill.png #DESIRED THUMBNAIL NAME
    - id: 7
      anchor_text: Cooperative Digital Resources Initiative
      url: /collections/cdri #PATH TO COLLECTION
      image:
        path_to_file: /img/CDRI_collection_thumb.jpg #DESIRED THUMBNAIL NAME
