---
homepage:
  collections:
    - id: 1
      anchor_text: Latin America Collection - Princeton Theological Seminary
      url: /collections/w9505163c #PATH TO COLLECTION
      image:
        path_to_file: /img/latin_america.png #DESIRED THUMBNAIL NAME
    - id: 2
      anchor_text: Moffett Korea Collection - Princeton Theological Seminary
      url: /collections/1831cm01x #PATH TO COLLECTION
      image:
        path_to_file: /img/moffett_korea.png #DESIRED THUMBNAIL NAME
    - id: 3
      anchor_text: T.F. Torrance Collection of Antiquarian Books - Princeton Theological Seminary
      url: /collections/hm50tt05r #PATH TO COLLECTION
      image:
        path_to_file: /img/tf_torrance.png #DESIRED THUMBNAIL NAME
    - id: 4
      anchor_text: The W. H. Dub Jackson Digital Materials Collection - Southwestern Baptist Theological Seminary Libraries
      url: /collections/9019s3627 #PATH TO COLLECTION
      image:
        path_to_file: /img/whdub.png #DESIRED THUMBNAIL NAME
    - id: 5
      anchor_text: The L.R. Scarborough Digital Materials Collection - Southwestern Baptist Theological Seminary Libraries
      url: /collections/ft848r32p #PATH TO COLLECTION
      image:
        path_to_file: /img/lrscarborough.png #DESIRED THUMBNAIL NAME
    - id: 6
      anchor_text: Robert Hamill Nassau Manuscript Collection - Princeton Theological Seminary
      url: /collections/9s1617330 #PATH TO COLLECTION
      image:
        path_to_file: /img/robert_hamill.png #DESIRED THUMBNAIL NAME
    - id: 7
      anchor_text: Cooperative Digital Resources Initiative
      url: /collections/rn3012530 #PATH TO COLLECTION
      image:
        path_to_file: /img/CDRI_collection_thumb.jpg #DESIRED THUMBNAIL NAME
