---
homepage:
  collections:
    - id: 1
      anchor_text: The Edgar J. Goodspeed Manuscript Collection
      anchor_text_two: University of Chicago Library
      url: /collections/the-edgar-j-goodspeed-manuscript-collection #PATH TO COLLECTION
      image:
        path_to_file: /img/uofc.jpg #DESIRED THUMBNAIL NAME
    - id: 2
      anchor_text: Atlanta-Rome District CME Church Collection
      anchor_text_two: Atlanta University Center Robert W. Woodruff Library
      url: /collections/atlanta-rome-district-cme-church-collection #PATH TO COLLECTION
      image:
        path_to_file: /img/atlanta.jpg #DESIRED THUMBNAIL NAME
    - id: 3
      anchor_text: Sermons of the Reverend Dr. William Augustus Jones, Jr.
      anchor_text_two: Brooklyn College Library
      url: /collections/sermons-of-the-reverend-dr-william-augustus-jones-jr #PATH TO COLLECTION
      image:
        path_to_file: /img/brooklyn-college-library.jpg #DESIRED THUMBNAIL NAME
    - id: 4
      anchor_text: American Religious Sounds Project
      anchor_text_two:
      url: /collections/american-religious-sounds-project #PATH TO COLLECTION
      image:
        path_to_file: /img/arsp-flute.jpg #DESIRED THUMBNAIL NAME
    - id: 5
      anchor_text: Philadelphia Congregations Early Records Project
      anchor_text_two:
      url: /collections/philadelphia-congregations-early-records-project #PATH TO COLLECTION
      image:
        path_to_file: /img/philadelphia.jpg #DESIRED THUMBNAIL NAME
    - id: 6
      anchor_text: Cooperative Digital Resources Initiative
      anchor_text_two:
      url: /collections/cooperative-digital-resources-initiative #PATH TO COLLECTION
      image:
        path_to_file: /img/CDRI_collection_thumb.jpg #DESIRED THUMBNAIL NAME

  exhibits:
    - id: 1
      anchor_text: The Life and Ministry of Charles Wesley
      anchor_text_two:
      url: /exhibitions/exhibits/show/the-life-and-ministry #PATH TO exhibit
      image:
        path_to_file: /img/life-and-ministry.jpg #DESIRED THUMBNAIL NAME
    - id: 2
      anchor_text: Wish You Were Here
      anchor_text_two:
      url: /exhibitions/exhibits/show/wish-you-were-here #PATH TO exhibit
      image:
        path_to_file: /img/wish-you-were-here.jpg #DESIRED THUMBNAIL NAME
    - id: 3
      anchor_text: 'Look Back in Anger: Anger, Religion, and Morality through the Ages'
      anchor_text_two:
      url: /exhibitions/exhibits/show/look-back-in-anger #PATH TO exhibit
      image:
        path_to_file: /img/look-back-in-anger.jpg #DESIRED THUMBNAIL NAME
