---
homepage:
  collections:
    - id: 1
      anchor_text: Latin America Collection - Princeton Theological Seminary
      url: /collections/latin-america-collection #PATH TO COLLECTION
      image:
        path_to_file: /img/latin_america.png #DESIRED THUMBNAIL NAME
    - id: 3
      anchor_text: Philadelphia Congregations Early Records Project
      url: /collections/philadelphia-congregations-early-records-project #PATH TO COLLECTION
      image:
        path_to_file: /img/philadelphia.jpg #DESIRED THUMBNAIL NAME
    - id: 4
      anchor_text: The March on Washington, 1963 - Union Presbyterian Seminary Library
      url: /collections/the-march-on-washington-1963 #PATH TO COLLECTION
      image:
        path_to_file: /img/the-march-on-wash-ups.jpg #DESIRED THUMBNAIL NAME
    - id: 5
      anchor_text: Collection of Free Church Literature - Trinity International University Rolfing Library
      url: /collections/collection-of-free-church-literature #PATH TO COLLECTION
      image:
        path_to_file: /img/free-churchliterature.jpg #DESIRED THUMBNAIL NAME
    - id: 6
      anchor_text: Temple of Religion & Tower of Peace - Graduate Theological Union
      url: /collections/temple-of-religion-and-tower-of-peace-1938-1940 #PATH TO COLLECTION
      image:
        path_to_file: /img/temple-of-religion.jpg #DESIRED THUMBNAIL NAME
    - id: 7
      anchor_text: The L.R. Scarborough Digital Materials Collection - Southwestern Baptist Theological Seminary Libraries
      url: /collections/the-l-r-scarborough-digital-materials-collection #PATH TO COLLECTION
      image:
        path_to_file: /img/lrscarborough.jpg #DESIRED THUMBNAIL NAME
    - id: 8
      anchor_text: The Methodist Manuscripts Collection - Garrett-Evangelical Theological Seminary Styberg Library
      url: /collections/the-methodist-manuscripts-collection #PATH TO COLLECTION
      image:
        path_to_file: /img/methodist-manuscripts.jpg #DESIRED THUMBNAIL NAME
    - id: 9
      anchor_text: Cooperative Digital Resources Initiative
      url: /collections/cooperative-digital-resources-initiative #PATH TO COLLECTION
      image:
        path_to_file: /img/CDRI_collection_thumb.jpg #DESIRED THUMBNAIL NAME
