---
- name: Download 64 bit Site24x7 agent from public URL
  get_url:
    url: https://staticdownloads.site24x7.com/server/Site24x7_Linux_64bit.install
    dest: /tmp/Site24x7_Linux_64bit.install
    mode: 0755
  when: ansible_machine == "x86_64"

- name : Install 64 bit Site24x7 agent in the server
  shell: /tmp/Site24x7_Linux_64bit.install -i -key={{ site24x7_device_key }} -f
  when: (ansible_machine == "x86_64" and site24x7_proxy == "NONE")

- name : Install 64 bit Site24x7 agent in the server
  shell: /tmp/Site24x7_Linux_64bit.install -i -key={{ site24x7_device_key }} -f -proxy={{ site24x7_proxy }}
  when: (ansible_machine == "x86_64" and site24x7_proxy != "NONE")

- service: name=site24x7monagent state=restarted
  when: ansible_machine == "x86_64"

