# alts should be downcase
terms:
  - id: Collection
    term: Collection
    alts: []
    active: true
  - id: Dataset
    term: Dataset
    alts: []
    active: true
  - id: Event
    term: Event
    alts: []
    active: true
  - id: Image
    term: Image
    alts: []
    active: true
  - id: InteractiveResource
    term: Interactive Resource
    alts: ['interactiveresource']
    active: true
  - id: MovingImage
    term: Moving Image
    alts: ['movingimage','video']
    active: true
  - id: PhysicalObject
    term: Physical Object
    alts: ['physicalobject']
    active: true
  - id: Service
    term: Service
    alts: []
    active: true
  - id: Software
    term: Software
    alts: []
    active: true
  - id: Sound
    term: Sound
    alts: ['audio']
    active: true
  - id: StillImage
    term: Still Image
    alts: ['stillimage', 'photograph', 'picture']
    active: true
  - id: Text
    term: Text
    alts: []
    active: true