---
- name: install ffmpeg libraries
  become: yes
  package: name={{ item }} state=present
  with_items:
      - autoconf
      - automake
      - cmake
      # - freetype-devel
      - gcc
      # - gcc-c++
      - git
      - libtool
      - make
      - mercurial
      - nasm
      # - pkgconfig
      # - zlib-devel

- name: remove package ffmpeg
  become: yes
  package: name=ffmpeg state=absent

- name: create sources dir
  become: yes
  file: owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=directory path={{ ffmpeg_path }}

- name: ff add ldconfig for /usr/local/lib
  become: yes
  copy: dest=/etc/ld.so.conf.d/usr-local.conf content=/usr/local/lib owner=root group=root mode=0644 

- name: download nasm
  become: yes
  shell: |
    curl -O https://www.nasm.us/pub/nasm/releasebuilds/2.13.01/nasm-2.13.01.tar.gz
    tar -xvzf nasm-2.13.01.tar.gz
    cd nasm-2.13.01/
    ./configure
    make
    make install
  creates: /usr/bin/nasm
