---
- name: clone ffmpeg source
  git: repo=git://source.ffmpeg.org/ffmpeg depth=1 accept_hostkey=yes dest={{ ffmpeg_path }}/ffmpeg force=yes


- name: configure ffmpeg
  shell: cd {{ ffmpeg_path }}/ffmpeg && PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --extra-libs="-ldl" --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264
  args:
    creates: /usr/local/bin/ffmpeg


- name: make ffmpeg
  shell: cd {{ ffmpeg_path }}/ffmpeg && make 
  args:
    creates: /usr/local/bin/ffmpeg


- name: install ffmpeg
  become: yes
  shell: cd {{ ffmpeg_path }}/ffmpeg && make install
  args:
    creates: /usr/local/bin/ffmpeg


- name: clean the ffmpeg repo
  become: yes
  shell: cd {{ ffmpeg_path }}/ffmpeg && make distclean
  args:
    creates: /usr/local/bin/ffmpeg


- name: link new ffmpeg
  become: yes
  shell: ldconfig
  args:
    creates: /usr/local/bin/ffmpeg

