---
- name: clone fdk-aac source
  git: repo=https://github.com/mstorsjo/fdk-aac.git depth=1 accept_hostkey=yes dest={{ ffmpeg_path }}/fdk-aac force=yes

- name: clean the fdk-aac repo
  shell: cd {{ ffmpeg_path }}/fdk-aac && autoreconf -fiv
  args:
    creates: /usr/local/lib/libfdk-aac.a

- name: configure fdk-aac
  shell: cd {{ ffmpeg_path }}/fdk-aac && ./configure --disable-shared creates={{ ffmpeg_path }}/fdk-aac/Makefile
  args:
    creates: /usr/local/lib/libfdk-aac.a

- name: make fdk-aac
  shell: cd {{ ffmpeg_path }}/fdk-aac && make 
  args:
    creates: /usr/local/lib/libfdk-aac.a

- name: install fdk-aac
  become: yes
  shell: cd {{ ffmpeg_path }}/fdk-aac && make install
  args:
    creates: /usr/local/lib/libfdk-aac.a

- name: clean the fkd-aac repo
  become: yes
  shell: cd {{ ffmpeg_path }}/fdk-aac && make distclean
  args:
    creates: /usr/local/lib/libfdk-aac.a
