---
- name: download ogg source
  get_url: url=http://downloads.xiph.org/releases/ogg/libogg-1.3.1.tar.gz dest={{ ffmpeg_path }}/libogg-1.3.1.tar.gz

- name: unzip ogg source
  unarchive: src={{ ffmpeg_path }}/libogg-1.3.1.tar.gz dest={{ ffmpeg_path }}/ creates={{ ffmpeg_path }}/libogg-1.3.1/compile.c copy=no
  args:
    creates: /usr/local/lib/libogg.a

- name: configure ogg
  shell: cd {{ ffmpeg_path }}/libogg-1.3.1 && ./configure creates={{ ffmpeg_path }}/libogg-1.3.1/Makefile
  args:
    creates: /usr/local/lib/libogg.a

- name: make ogg
  shell: cd {{ ffmpeg_path }}/libogg-1.3.1 && make 
  args:
    creates: /usr/local/lib/libogg.a

- name: install ogg
  become: yes
  shell: cd {{ ffmpeg_path }}/libogg-1.3.1 && make install
  args:
    creates: /usr/local/lib/libogg.a
