---
- name: download libopus source
  get_url: url=http://downloads.xiph.org/releases/opus/opus-1.0.3.tar.gz dest={{ ffmpeg_path }}/opus-1.0.3.tar.gz

- name: unzip libopus source
  unarchive: src={{ ffmpeg_path }}/opus-1.0.3.tar.gz dest={{ ffmpeg_path }}/ creates={{ ffmpeg_path }}/opus-1.0.3/compile.c copy=no
  args:
    creates: /usr/local/lib/libopus.a

- name: configure libopus
  shell: cd {{ ffmpeg_path }}/opus-1.0.3 && ./configure --disable-shared creates={{ ffmpeg_path }}/opus-1.0.3/Makefile
  args:
    creates: /usr/local/lib/libopus.a

- name: make libopus
  shell: cd {{ ffmpeg_path }}/opus-1.0.3 && make 
  args:
    creates: /usr/local/lib/libopus.a

- name: install libopus
  become: yes
  shell: cd {{ ffmpeg_path }}/opus-1.0.3 && make install
  args:
    creates: /usr/local/lib/libopus.a
