---
- name: clone libvpx source
  git: repo=https://chromium.googlesource.com/webm/libvpx.git depth=1 dest={{ ffmpeg_path }}/libvpx force=yes

- name: configure libvpx
  shell: cd {{ ffmpeg_path }}/libvpx && ./configure --disable-examples creates={{ ffmpeg_path }}/libvpx/Makefile
  args:
    creates: /usr/local/lib/libvpx.a

- name: make libvpx
  shell: cd {{ ffmpeg_path }}/libvpx && make 
  args:
    creates: /usr/local/lib/libvpx.a

- name: install libvpx
  become: yes
  shell: cd {{ ffmpeg_path }}/libvpx && make install
  args:
    creates: /usr/local/lib/libvpx.a

- name: clean the libvpx repo
  become: yes
  shell: cd {{ ffmpeg_path }}/libvpx && make distclean
  args:
    creates: /usr/local/lib/libvpx.a
