---
- name: clone x264 source
  git: repo=git://git.videolan.org/x264 depth=1 accept_hostkey=yes dest={{ ffmpeg_path }}/x264 force=yes

- name: configure x264
  shell: cd {{ ffmpeg_path }}/x264 && ./configure --enable-static 
  args:
    creates: /usr/local/bin/x264
 
- name: make x264
  shell: cd {{ ffmpeg_path }}/x264 && make 
  args:
    creates: /usr/local/bin/x264
 
- name: install x264
  become: yes
  shell: cd {{ ffmpeg_path }}/x264 && make install
  args:
    creates: /usr/local/bin/x264
 
- name: clean the x264 repo
  become: yes
  shell: cd {{ ffmpeg_path }}/x264 && make distclean
  args:
    creates: /usr/local/bin/x264
 
