---
- name: clone yasm source
  git: repo=https://github.com/yasm/yasm.git depth=1 accept_hostkey=yes dest={{ ffmpeg_path }}/yasm force=yes

- name: reconfigure the yasm repo
  shell: cd {{ ffmpeg_path }}/yasm && autoreconf -fiv # ./autogen.sh
  args:
    creates: /usr/local/bin/yasm

- name: configure yasm
  shell: cd {{ ffmpeg_path }}/yasm && ./configure
  args:
    creates: /usr/local/bin/yasm

- name: make yasm
  shell: cd {{ ffmpeg_path }}/yasm && make
  args:
    creates: /usr/local/bin/yasm

- name: install yasm
  become: yes
  shell: cd {{ ffmpeg_path }}/yasm && make install
  args:
    creates: /usr/local/bin/yasm

- name: clean the yasm repo
  become: yes
  shell: cd {{ ffmpeg_path }}/yasm && make distclean # ./autogen.sh
  args:
    creates: /usr/local/bin/yasm
