development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: atla_digital_library_staging

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: atla_digital_library_production
