development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://fcrepo:8080/fcrepo/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://fcrepo:8080/fcrepo/rest
  base_path: /test
staging:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://fcrepo:8080/fedora/rest
  base_path: /prod
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://fcrepo:8080/fedora/rest
  base_path: /prod
