development:
  host: redis
  port: 6379
test:
  host: redis
  port: 6379
staging:
  host: <%= ENV.fetch('REDIS_URL', 'localhost') %>
  port: 6379
production:
  host: <%= ENV.fetch('REDIS_URL', 'localhost') %>
  port: 6379
