development:
  host: redis
  port: 6379
test:
  host: redis
  port: 6379
staging:
  host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  port: 6379
  password: <%= ENV.fetch('REDIS_PASSWORD', nil) %>
production:
  host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  port: 6379
  password: <%= ENV.fetch('REDIS_PASSWORD', nil) %>
