# This is a sample config file that points to a solr server for each environment
development:
  url: http://solr:8983/solr/hydra-development
test:
  url: http://solr:8983/solr/hydra-test
production:
  url: http://solr:8983/solr/hydra-production
