---
# Note: These are dependent on the /opt mount created in ec2_housekeeping
# TODO
# add backup and cleanup scripts to crontab
# be sure backup_opt runs at least an hour after the postgres backups

- name: get EC2 instance_id
  action: ec2_facts
  register: instance_facts

- name: lookup volume_ID for data volume # used in snapshot_backup.j2 template
  # NOTE: the volume was created with the instance in order to set delete_on_terminate
  # but you need to run this to get the volume id to use for AWS snapshots
  ec2_vol:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    instance: "{{ instance_facts.ansible_facts.ansible_ec2_instance_id }}"
    region: "{{ instance_facts.ansible_facts.ansible_ec2_placement_region }}"
    device_name: /dev/sdf
    state: present
  register: ec2_vol_1

- name: add ec2 directory
  become: yes
  file: owner=root group=root path=/etc/ec2-backups state=directory

- name: add snapshot delete key
  become: yes
  template: src=delete_key.j2 dest=/etc/ec2-backups/delete_key owner=root group=root mode=0600

- name: add snapshot delete secret
  become: yes
  template: src=delete_secret.j2 dest=/etc/ec2-backups/delete_secret owner=root group=root mode=0600

- name: add snapshot cleanup (delete) script
  become: yes
  template: src=snapshot_cleanup.j2 dest=/etc/ec2-backups/clean_up_snapshots.sh owner=root group=root mode=0744

- name: add snapshot create credentials
  become: yes
  template: src=snapshot_creds.j2 dest=/etc/ec2-backups/snapshot_creds owner=root group=root mode=0600

- name: add snapshot create (backup) script
  become: yes
  template: src=snapshot_backup.j2 dest=/etc/ec2-backups/backup_opt.sh owner=root group=root mode=0744

- name: add snapshot cleanup cron job
  become: yes
  cron: name="delete ec2 old snapshots" user=root job="/etc/ec2-backups/clean_up_snapshots.sh" minute="5" hour="2" state=present

- name: add snapshot create cron job
  become: yes
  cron: name="ec2 snapshot backup" user=root job="/etc/ec2-backups/backup_opt.sh" minute="15" hour="1" state=present
