---
- name: download libpng source
  get_url: url=https://sourceforge.net/projects/libpng/files/libpng16/older-releases/{{ libpng_ver }}/libpng-{{ libpng_ver }}.tar.gz dest={{ magick_path }}/libpng-{{ libpng_ver }}.tar.gz

- name: unzip libpng source
  unarchive: src={{ magick_path }}/libpng-{{ libpng_ver }}.tar.gz dest={{ magick_path }}/ creates={{ magick_path }}/libpng-{{ libpng_ver }} copy=no
  args:
    creates: /usr/local/lib/libpng.a

- name: configure libpng
  shell: cd {{ magick_path }}/libpng-{{ libpng_ver }} && ./configure
  args:
    creates: /usr/local/lib/libpng.a

- name: make libpng
  shell: cd {{ magick_path }}/libpng-{{ libpng_ver }} && make 
  args:
    creates: /usr/local/lib/libpng.a

- name: install libpng
  become: yes
  shell: cd {{ magick_path }}/libpng-{{ libpng_ver }} && make install
  args:
    creates: /usr/local/lib/libpng.a
