---
- name: download libtiff source
  get_url: url=http://download.osgeo.org/libtiff/tiff-{{ libtiff_ver }}.tar.gz dest={{ magick_path }}/tiff-{{ libtiff_ver }}.tar.gz

- name: unzip libtiff source
  unarchive: src={{ magick_path }}/tiff-{{ libtiff_ver }}.tar.gz dest={{ magick_path }}/ creates={{ magick_path }}/tiff-{{ libtiff_ver }} copy=no
  args:
    creates: /usr/local/lib/libtiff.a

- name: configure libtiff
  shell: cd {{ magick_path }}/tiff-{{ libtiff_ver }} && ./configure
  args:
    creates: /usr/local/lib/libtiff.a

- name: make libtiff
  shell: cd {{ magick_path }}/tiff-{{ libtiff_ver }} && make 
  args:
    creates: /usr/local/lib/libtiff.a

- name: install libtiff
  become: yes
  shell: cd {{ magick_path }}/tiff-{{ libtiff_ver }} && make install
  args:
    creates: /usr/local/lib/libtiff.a
