---
- name: download openjpg source
  get_url: url=http://downloads.sourceforge.net/project/openjpeg.mirror/{{ openjpg_ver }}/openjpeg-{{ openjpg_ver }}.tar.gz dest={{ magick_path }}/openjpeg-{{ openjpg_ver }}.tar.gz

- name: unzip openjpg source
  unarchive: src={{ magick_path }}/openjpeg-{{ openjpg_ver }}.tar.gz dest={{ magick_path }}/ creates={{ magick_path }}/openjpeg-version.{{ openjpg_ver }} copy=no
  args:
    creates: /usr/local/lib/libopenjp2.so

- name: configure openjpg
  shell: cd {{ magick_path }}/openjpeg-{{ openjpg_ver }} && cmake ./
  args:
    creates: /usr/local/lib/libopenjp2.so

- name: make openjpg
  shell: cd {{ magick_path }}/openjpeg-{{ openjpg_ver }} && make 
  args:
    creates: /usr/local/lib/libopenjp2.so

- name: install openjpg
  become: yes
  shell: cd {{ magick_path }}/openjpeg-{{ openjpg_ver }} && make install
  args:
    creates: /usr/local/lib/libopenjp2.so
