---
- name: copy delayed_job init script
  template: src=delayed_job.j2 dest=/etc/init.d/delayed_job mode=0755
  become: yes

# dont try and start until after deploy
#- name: start delayed_job 
#  service: name=delayed_job state=started enabled=yes
#  become: yes
