---
- name: copy resque init script
  template: src=sidekiq.j2 dest=/etc/init.d/sidekiq mode=0755
  become: yes

# dont try and start until after deploy
#- name: start sidekiq
#  service: name=sidekiq state=started enabled=yes
#  become: yes
