replicaCount: 2

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: aws-efs
derivativesVolume:
  storageClass: aws-efs
uploadsVolume:
  storageClass: aws-efs

securityContext: &secValues
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
podSecurityContext: &podSecValues
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: "OnRootMismatch"

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files

ingress:
  enabled: true
  hosts:
    - host: atla.notch8.cloud
      paths:
        - path: /
    - host: dl.atla.com
      paths:
        - path: /

extraEnvVars: &envVars
  - name: CONFDIR
    value: "/app/samvera/hyrax-webapp/solr/conf"
  - name: DATABASE_ADAPTER
    value: postgresql
  - name: DATABASE_HOST
    value: hyrax20181216.cn4nhxyoxlnu.us-west-2.rds.amazonaws.com
  - name: DATABASE_NAME
    value: hydra
  - name: DATABASE_PASSWORD
    value: $DATABASE_PASSWORD
  - name: DATABASE_USER
    value: hydra_user
  - name: FCREPO_BASE_PATH
    value: /prod
  - name: FCREPO_HOST
    value: fcrepo.default
  - name: FCREPO_PATH
    value: /rest
  - name: FEDORA_URL
    value: http://fcrepo.default:8080/rest
  - name: INITIAL_ADMIN_EMAIL
    value: support@notch8.com
  - name: INITIAL_ADMIN_PASSWORD
    value: testing123
  - name: IN_DOCKER
    value: "true"
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_MAX_THREADS
    value: "5"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: HYRAX_FITS_PATH
    value: /app/fits/fits.sh
  - name: SMTP_ADDRESS
    value: email-smtp.us-east-1.amazonaws.com
  - name: SMTP_DOMAIN
    value: atla.com
  - name: SMTP_ENABLED
    value: "true"
  - name: SMTP_PASSWORD
    value: $SMTP_PASSWORD_PROD
  - name: SMTP_PORT
    value: "465"
  - name: SMTP_TYPE
    value: login
  - name: SMTP_USER_NAME
    value: AKIAJ2P27AKGIPDXBOUA
  - name: SMTP_STARTTLS
    value: "true"
  - name: SOLR_ADMIN_USER
    value: admin
  - name: SOLR_COLLECTION_NAME
    value: hyrax
  - name: SOLR_CONFIGSET_NAME
    value: hyrax
  - name: SOLR_HOST
    value: solr.default
  - name: SOLR_PORT
    value: "8983"
  - name: SOLR_URL
    value: $SOLR_URL_PROD
  - name: RAILS_CACHE_STORE_URL
    value: redis://:production@production-redis-master:6379/hyrax
  - name: REDIS_PASSWORD
    value: production
  - name: REDIS_HOST
    value: production-redis-master
  - name: REDIS_URL
    value: redis://:production@production-redis-master
  - name: SECRET_KEY_BASE
    value: $SECRET_KEY_BASE_PROD
  - name: SENTRY_DSN
    value: $SENTRY_DSN
  - name: DISABLE_SPRING
    value: "1"


worker:
  replicaCount: 1
  securityContext: *secValues
  extraVolumeMounts: *volMounts
  extraEnvVars: *envVars
  podSecurityContext: *podSecValues

imagePullSecrets:
  - name: gitlab

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

fcrepo:
  enabled: false
postgresql:
  enabled: false
solr:
  enabled: false
redis:
  cluster:
    enabled: false
  password: production

externalFcrepoHost: fcrepo.default.svc.cluster.local
externalPostgresql:
  host: hyrax20181216.cn4nhxyoxlnu.us-west-2.rds.amazonaws.com
  username: hydra_user
  password: $DATABASE_PASSWORD
  database: hydra

externalSolrHost: solr.default.svc.cluster.local
externalSolrUser: admin
externalSolrCollection: "hyrax"
externalSolrPassword: $SOLR_PASSWORD
