replicaCount: 2

resources:
  requests:
    memory: '1Gi'
    cpu: '250m'
  limits:
    memory: '2Gi'
    cpu: '1000m'

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: aws-efs
derivativesVolume:
  storageClass: aws-efs
uploadsVolume:
  storageClass: aws-efs

securityContext: &secValues
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0

podSecurityContext: &podSecValues
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: 'OnRootMismatch'

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files
  - name: uploads
    mountPath: /opt/cdri
    subPath: cdri

ingress:
  enabled: true
  hosts:
    - host: atla.notch8.cloud
      paths:
        - path: /
    - host: dl.atla.com
      paths:
        - path: /

extraEnvVars: &envVars
  - name: CONFDIR
    value: '/app/samvera/hyrax-webapp/solr/conf'
  - name: DB_USERNAME
    value: 'hydra_user'
  - name: DISABLE_SPRING
    value: '1'
  - name: HYRAX_FITS_PATH
    value: /app/fits/fits.sh
  - name: INITIAL_ADMIN_EMAIL
    value: support@notch8.com
  - name: INITIAL_ADMIN_PASSWORD
    value: testing123
  - name: IN_DOCKER
    value: 'true'
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_CACHE_STORE_URL
    value: redis://:$REDIS_PASSWORD@production-redis-master:6379/hyrax
  - name: RAILS_LOG_TO_STDOUT
    value: 'true'
  - name: RAILS_MAX_THREADS
    value: '5'
  - name: RAILS_SERVE_STATIC_FILES
    value: 'true'
  - name: SENTRY_DSN
    value: https://bd539e7a5436434dac5abfdab595731a@o1008683.ingest.sentry.io/6745022
  - name: SMTP_ADDRESS
    value: email-smtp.us-east-1.amazonaws.com
  - name: SMTP_DOMAIN
    value: atla.com
  - name: SMTP_ENABLED
    value: 'true'
  - name: SMTP_PASSWORD
    value: $SMTP_PASSWORD
  - name: SMTP_PORT
    value: '465'
  - name: SMTP_STARTTLS
    value: 'true'
  - name: SMTP_TYPE
    value: login
  - name: SMTP_USER_NAME
    value: AKIAJ2P27AKGIPDXBOUA
  - name: SOLR_CONFIGSET_NAME
    value: 'production-hyrax'

worker:
  replicaCount: 1
  resources:
    requests:
      memory: '1Gi'
      cpu: '250m'
    limits:
      memory: '2Gi'
      cpu: '1000m'
  securityContext: *secValues
  extraVolumeMounts: *volMounts
  extraEnvVars: *envVars
  podSecurityContext: *podSecValues

imagePullSecrets:
  - name: github

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

postgresql:
  enabled: false
externalPostgresql:
  host: 'hyrax20181216.cn4nhxyoxlnu.us-west-2.rds.amazonaws.com'
  database: 'hydra'
  username: 'hydra_user'
  password: $DATABASE_PASSWORD

fcrepo:
  resources:
    limits:
      memory: '4Gi'
      cpu: '2'
    requests:
      memory: '2Gi'
      cpu: '1'
  enabled: false
  restPath: '/rest'
externalFcrepoHost: 'fcrepo.default.svc.cluster.local'
fcrepoBasePathOverride: '/prod'

redis:
  cluster:
    enabled: false
  password: $REDIS_PASSWORD

solr:
  enabled: false
externalSolrHost: 'solr.default.svc.cluster.local'
externalSolrUser: 'admin'
externalSolrPassword: $SOLR_ADMIN_PASSWORD
externalSolrCollection: 'hyrax'
